### ISSUE TITLE
Real time spark

### ISSUE THREAD

**Issue by szepeviktor** [holman/spark#81]
Do you know any project that calculates min and max values in real time and updates the graph thus showing only tha last `N` values?
E.g. `ping google.com 2>&1 | sed -n 's|.* bytes from .* time=\([0-9.]*\) .*|\1|gp'`

**Comment by dotwaffle** [comment]
With the exception of a watch loop, no... However for that particular
example you could use prettyping:

https://bitbucket.org/denilsonsa/small_scripts/src/tip/prettyping.sh

**Comment by szepeviktor** [comment]
Oh! Thank you!
I've found https://github.com/dkogan/feedgnuplot

**Comment by szepeviktor** [comment]
I suggest you [this kind of script header](https://bitbucket.org/denilsonsa/small_scripts/raw/b20d762b9c1a0d250ddbd8e26850df62d84b1559/prettyping.sh) for bash/python anything that handles hashmark:

```bash
#!/bin/bash
#
# Restart PHP-FPM and Apache dependently
#
# VERSION :0.1
# DATE :2014-12-12
# AUTHOR :Viktor Szépe <viktor@szepe.net>
# LICENSE :The MIT License (MIT)
# URL :https://github.com/szepeviktor/debian-server-tools
# BASH-VERSION :4.2+
# LOCATION :/usr/local/sbin/webrestart.sh
# DEPENDS :apt-get install php5-fpm apache2
```

It can easly parsed:
https://github.com/szepeviktor/debian-server-tools/blob/master/install.sh#L20-L37

**Comment by szepeviktor** [comment]
Finally

```bash
ping -n google.com|sed -u -n 's|^.* bytes from .*: icmp_req=\([0-9]\+\) .* time=\([0-9.]\+\) .*$|\1 \2|gp'|feedgnuplot --terminal 'dumb 120,40' --stream --lines -xlen 30 --set "xtics 10" --domain
```
