### ISSUE TITLE
Does not work on my Mac 10.10, iTerm2 (using agnoster theme of Zsh)

### ISSUE THREAD

**Issue by indrayam** [holman/spark#85]
The graphs do not line up on a flat straight line. So looks odd. Not sure what I am doing wrong.

**Comment by ncanceill** [comment]
Could be your font. Have you try changing it?

**Comment by apretto** [comment]
I had the same problem on OS X Yosemite.

The terminal was using the Monaco font. Changing to use Menlo made fixed the issue of some of the bars not aligning.

**Comment by pboling** [comment]
I am seeing bars fall below the apparent bottom of the graph, as if somehow they have a negative origin.  I am on Yosemite, using iTerm 2 and bash.  Going to try a new font.

**Comment by rogeruiz** [comment]
I'm seeing the same thing here. Here's an example of the output and a screenshot. 
<img width="412" alt="screenshot 2015-09-10 20 40 08" src="https://cloud.githubusercontent.com/assets/706004/9804484/2c461006-57fc-11e5-873c-85c2189e14c4.png">
```
❯❯❯❯❯❯❯ clocker data | grep -oEi '\d+\.\d+' | SPARK_MIN=0 spark
▁▃▃▁▃▃▃▅▅▅▁▅▅▂▃▄▂▂▅▆▃▅▆▇▆▆▆█▇▃▁▂▁▃▆▅
```

**Comment by ColbyAley** [comment]
I am seeing this too, in iTerm 2 both inside and out of Tmux. :cry:

**Comment by dasilvacontin** [comment]
Same here.

**Comment by casidiablo** [comment]
Same here. Works fine on Terminal.

**Comment by rogeruiz** [comment]
Hmmm. It might be worth opening an issue in iTerm's repo on this and tie them together. Seems like it's not necessarily a bug in `spark` so much.

**Comment by casidiablo** [comment]
@rogeruiz Yeah, makes sense. By the way, what's the name of the font you were using in your screenshot?

**Comment by rogeruiz** [comment]
@casidiablo It's M+ 2m regular. It's open source and [you can download it here](https://mplus-fonts.osdn.jp/about-en.html#multiweight)

**Comment by rogeruiz** [comment]
iTerm uses Gitlab for their issues so I can't cross-post it using Github's fancy `#XXX` shortcuts. Here's a [link to the issue on Gitlab](https://gitlab.com/gnachman/iterm2/issues/4152). :+1:

**Comment by holman** [comment]
Thanks for creating and linking the issue, @rogeruiz! I'm going to tentatively close this issue out. I'm subscribed on that thread, and if it ends up being a problem with Spark itself we can reopen and make some fixes.
