### ISSUE TITLE
additional space between graphs if using in tmux.

### ISSUE THREAD

**Issue by shivanju** [holman/spark#87]

**Comment by holman** [comment]
What's the current look of it in tmux?

**Comment by shivanju** [comment]
![screenshot from 2015-06-23 17 54 06](https://cloud.githubusercontent.com/assets/6336954/8305906/fbfae0c0-19d0-11e5-80e0-08eecd87247c.png)

sorry if I am missing some configuration. I am new to linux.

**Comment by CristianCantoro** [comment]
I can not reproduce this on my sistem with:
* Ubuntu 16.04 LTS
* spark v. 1.0.0
* tmux v. 2.1
